### ISSUE TITLE
Jekyll error

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#21]
@tobyhodges 

I just tried to build locally and got below error.

- Should I try to reinstall Jekyll?
- If so, is there a good way to remove old installations?

```
tischer@Christians-MBP training-resources (master) $ make serve
bundle install --path .vendor/bundle && bundle update && bundle exec jekyll serve
Traceback (most recent call last):
	31: from /Users/tischer/.gem/ruby/2.6.0/bin/bundle:23:in `<main>'
	30: from /Users/tischer/.gem/ruby/2.6.0/bin/bundle:23:in `load'
	29: from /Users/tischer/.gem/ruby/2.6.0/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
	28: from /Users/tischer/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	27: from /Users/tischer/.gem/ruby/2.6.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
	26: from /Users/tischer/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
	25: from /Users/tischer/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	24: from /Users/tischer/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
	23: from /Users/tischer/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	22: from /Users/tischer/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	21: from /Users/tischer/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	20: from /Users/tischer/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:234:in `install'
	19: from /Users/tischer/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/settings.rb:144:in `temporary'
	18: from /Users/tischer/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:235:in `block in install'
	17: from /Users/tischer/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/install.rb:65:in `run'
	16: from /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	15: from /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /Users/tischer/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/installer.rb:4:in `<top (required)>'
	13: from /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/dependency_installer.rb:4:in `<top (required)>'
	10: from /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/package.rb:44:in `<top (required)>'
	 7: from /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/security.rb:12:in `<top (required)>'
	 4: from /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/openssl.rb:13:in `<top (required)>'
	 1: from /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/x86_64-darwin18/openssl.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (LoadError)
  Referenced from: /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/x86_64-darwin18/openssl.bundle
  Reason: image not found - /Users/tischer/.rbenv/versions/2.6.2/lib/ruby/2.6.0/x86_64-darwin18/openssl.bundle
make: *** [serve] Error 1
```

**Comment by tobyhodges** [comment]
Did you update your OS recently? You can try running [`gem pristine`](https://guides.rubygems.org/command-reference/#gem-pristine) from the root directory of the lesson repo.

**Comment by tobyhodges** [comment]
okay, looks like you need to install openssl. I usually do that with Homebrew:

```
brew update
brew install openssl
```

**Comment by tischi** [comment]
Strange, seems I had it already...

```
tischer@Christians-MBP training-resources (master) $ brew install openssl
Error: openssl@1.1 1.1.1g is already installed
To upgrade to 1.1.1h, run `brew upgrade openssl@1.1`
```

Upgrade?!

**Comment by tobyhodges** [comment]
You may be interested in #31.
